-- Migration: 012_payments.sql
-- PhonePe Payment Gateway Integration
-- Created: 2026-01-07

-- ============================================================================
-- PAYMENTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Transaction IDs
    merchant_transaction_id TEXT UNIQUE NOT NULL,
    phonepe_transaction_id TEXT,
    
    -- Link to sale (optional - set after payment confirmed)
    sale_id UUID REFERENCES sales(id) ON DELETE SET NULL,
    
    -- Payment details
    amount INTEGER NOT NULL, -- Amount in paise (100 = ₹1)
    currency TEXT DEFAULT 'INR',
    
    -- Status tracking
    status TEXT DEFAULT 'INITIATED' CHECK (status IN (
        'INITIATED',
        'PENDING', 
        'SUCCESS',
        'FAILED',
        'REFUNDED'
    )),
    
    -- Customer info
    customer_phone TEXT,
    
    -- PhonePe response details
    payment_instrument TEXT, -- UPI, CARD, WALLET, etc.
    response_code TEXT,
    response_message TEXT,
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_sale_id ON payments(sale_id);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_phonepe_txn ON payments(phonepe_transaction_id);

-- ============================================================================
-- TRIGGER: Auto-update updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION update_payments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_payments_updated_at ON payments;
CREATE TRIGGER trigger_payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION update_payments_updated_at();

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read payments
CREATE POLICY "payments_select_policy" ON payments
    FOR SELECT
    USING (true);

-- Allow authenticated users to insert payments
CREATE POLICY "payments_insert_policy" ON payments
    FOR INSERT
    WITH CHECK (true);

-- Allow authenticated users to update payments
CREATE POLICY "payments_update_policy" ON payments
    FOR UPDATE
    USING (true);

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE payments IS 'PhonePe payment gateway transactions';
COMMENT ON COLUMN payments.merchant_transaction_id IS 'Unique transaction ID generated by Luminila (format: LMLA_orderid_timestamp)';
COMMENT ON COLUMN payments.phonepe_transaction_id IS 'Transaction ID returned by PhonePe after payment';
COMMENT ON COLUMN payments.amount IS 'Payment amount in paise (multiply by 100 for rupees)';
COMMENT ON COLUMN payments.payment_instrument IS 'Payment method used: UPI, CARD, WALLET, NET_BANKING, etc.';
